#!/usr/bin/expect

set timeout 1
spawn ./build/acyclic

expect_before {
    timeout { exit 1 }
}

expect "acyclic started"
expect "$ "
send "\t"
expect ""
send "\r"

expect "$ "
send "\t\t"
expect "help test greet rocky rockie same sametext exit"
send "\r"

expect "$ "
send "r\t"
expect ""
send "\t"
expect "rocky rockie"
send "\r"
expect "command not found"

expect "$ "
send "h\t"
expect "elp "
send "g\t"
expect "reet "
send "\r"

expect "$ "
send "greet me\r"
expect "hello from me"

expect "$ "
send "help greet m\t"
send "e"
expect "help greet me"
send "\r"

expect "$ "
send "same\t\t"
expect "same sametext"
send "\r"
expect "no function assigned"

expect "$ "
send "test o\r"
expect "args: \\\[*test\\\] \\\[o\\\]"

expect "$ "
send "help 1 2 3 4\r"
expect "show greeting"
expect "$ "
send "help 1 2 3 4 5\r"
expect "max arg count reached"

expect "$ "
send "greet --fmt=\"%s %s\" \"Foo\" \"Bar\"\r"
expect "arg: greet"
expect "arg: --fmt=\"%s %s\""
expect "arg: \"Foo\""
expect "arg: \"Bar\""

expect "$ "
exit 0
